# Generated by Django 5.2.11 on 2026-02-19 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_perfil', models.CharField(choices=[('ENFERMAGEM', 'Enfermagem (Triagem)'), ('MEDICO', 'Médico (Monitoramento)'), ('ADMINISTRATIVO', 'Administrativo (Consulta)'), ('ADMIN', 'Administrador de Sistema (Full)')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidades', models.ManyToManyField(to='clinica.unidadesaude')),
            ],
        ),
    ]
