# Generated by Django 5.2.11 on 2026-02-19 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtendimentoTriagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_triagem', models.DateTimeField(auto_now_add=True)),
                ('protocolo', models.CharField(choices=[('NEWS', 'NEWS (Adulto)'), ('PEWS', 'PEWS (Pediátrico)'), ('MEOWS', 'MEOWS (Obstétrico)')], max_length=10)),
                ('freq_respiratoria', models.IntegerField(blank=True, null=True)),
                ('saturacao_o2', models.IntegerField(blank=True, null=True)),
                ('uso_o2_suplementar', models.BooleanField(default=False)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('pressao_sistolica', models.IntegerField(blank=True, null=True)),
                ('freq_cardiaca', models.IntegerField(blank=True, null=True)),
                ('nivel_consciencia', models.CharField(blank=True, max_length=50, null=True)),
                ('score_final', models.IntegerField(blank=True, null=True)),
                ('classificacao_risco', models.CharField(blank=True, max_length=20, null=True)),
                ('alerta_reconhecido', models.BooleanField(default=False)),
                ('enfermeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.unidadesaude')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
            ],
        ),
    ]
