# Generated by Django 5.2.11 on 2026-02-20 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_paciente_atendimentotriagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentotriagem',
            name='medico_reconheceu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_reconhecidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
