# Generated by Django 5.2.11 on 2026-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_atendimentotriagem_medico_reconheceu'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadesaude',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
