# Generated by Django 5.2.11 on 2026-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_unidadesaude_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacesso',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='perfilacesso',
            name='deve_trocar_senha',
            field=models.BooleanField(default=True),
        ),
    ]
