# Generated by Django 5.2.11 on 2026-02-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_perfilacesso_cpf_perfilacesso_deve_trocar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentotriagem',
            name='data_hora_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentotriagem',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
