# Generated by Django 5.2.11 on 2026-02-24 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_atendimentotriagem_data_hora_finalizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentotriagem',
            name='usuario_finalizou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
