# Generated by Django 5.2.11 on 2026-02-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_atendimentotriagem_usuario_finalizou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacesso',
            name='tipo_perfil',
            field=models.CharField(choices=[('ENFERMAGEM', 'Enfermagem (Triagem)'), ('MEDICO', 'Médico (Monitoramento)'), ('PADRAO', 'Padrão (Acesso Total Clínico)'), ('ADMINISTRATIVO', 'Administrativo (Consulta)'), ('ADMIN', 'Administrador de Sistema (Full)')], max_length=20),
        ),
    ]
