# Generated by Django 5.2.11 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_alter_perfilacesso_tipo_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimentotriagem',
            name='debito_urinario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimentotriagem',
            name='pressao_diastolica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
